name = "HAL"
prefix = "hal"
author = "HAL-Team"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "README*.md",  # Translated READMEs get moved to root in a hook (virtual file system)
    "LICENSE",
]

[version]
git_hash = 0

[lints.sqf]
command_case = false
if_not_else = false
select_parse_number = false
not_private = false
var_all_caps = false
unused = false
